import 'package:flutter/material.dart';

class LucideIcons {
  static const IconData landmark = Icons.account_balance;
  static const IconData mail = Icons.mail_outline;
  static const IconData lock = Icons.lock_outline;
  static const IconData eyeOff = Icons.visibility_off_outlined;
  static const IconData eye = Icons.visibility_outlined;
  static const IconData user = Icons.person_outline;
  static const IconData arrowLeft = Icons.arrow_back;
  static const IconData messageCircle = Icons.chat_bubble_outline;
  static const IconData chevronRight = Icons.chevron_right;
  static const IconData trash2 = Icons.delete_outline;
  static const IconData phoneCall = Icons.phone_forwarded;
  static const IconData mic = Icons.mic_none;
  static const IconData send = Icons.send;
  static const IconData volume2 = Icons.volume_up;
  static const IconData volumeX = Icons.volume_off;
  static const IconData search = Icons.search;
  static const IconData badgeCheck = Icons.verified;
  static const IconData clock = Icons.access_time;
  static const IconData history = Icons.history;
  static const IconData crown = Icons.workspace_premium;
  static const IconData shieldCheck = Icons.shield_outlined;
  static const IconData sparkles = Icons.auto_awesome;
  static const IconData check = Icons.check;
  static const IconData x = Icons.close;
  static const IconData phone = Icons.phone_outlined;
  static const IconData mapPin = Icons.map_outlined;
  static const IconData save = Icons.save_outlined;
  static const IconData keyRound = Icons.vpn_key_outlined;
  static const IconData chevronUp = Icons.keyboard_arrow_up;
  static const IconData chevronDown = Icons.keyboard_arrow_down;
  static const IconData logOut = Icons.logout;
  static const IconData trophy = Icons.emoji_events;
  static const IconData film = Icons.movie_outlined;
  static const IconData chevronLeft = Icons.chevron_left;
  static const IconData arrowRight = Icons.arrow_forward;
  static const IconData pause = Icons.pause;
  static const IconData play = Icons.play_arrow;
  static const IconData externalLink = Icons.open_in_new;
  static const IconData layoutGrid = Icons.grid_view;
  static const IconData searchX = Icons.search_off;
  static const IconData alertCircle = Icons.error_outline;
  static const IconData maximize2 = Icons.fullscreen;
}
